TRIALS = 5
TRIAL_LEN = 40#50000#500

NUM_ACCESS_POINTS = 3#9
NUM_USERS = 5#15#20
# ONLINE:
USERS_TO_CARE_ABOUT = NUM_USERS

NEGATIVE_REWARD = -300

AP_CAPACITY = 25
COMPUTATIONAL_DELAY_SCALING_FACTOR = 20

RUNNING_ON_COLAB = False
DIAG_DIRECTORY = "./diags/"